"""Fotografias de perfil, portafolio y moderacion

Revision ID: 0cfb1ba1a212
Revises: e1a2ec9cfcff
Create Date: 2026-08-20 14:51:31.382865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cfb1ba1a212'
down_revision = 'e1a2ec9cfcff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Ajuste manual: 'foto_moderation_status' y 'account_status' se agregan
    # como NOT NULL a tablas que ya tienen filas (los colaboradores DEMO).
    # SQLAlchemy default= solo aplica a INSERTs nuevos, no a las filas
    # existentes — sin server_default acá, esta migración fallaría al
    # aplicarse sobre una base con datos.
    op.create_table('portfolio_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collaborator_profile_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('fecha_subida', sa.DateTime(), nullable=False),
    sa.Column('moderation_status', sa.String(length=10), nullable=False),
    sa.Column('moderation_reason', sa.String(length=255), nullable=True),
    sa.Column('hash_exacto', sa.String(length=64), nullable=False),
    sa.Column('hash_perceptual', sa.String(length=64), nullable=True),
    sa.CheckConstraint("moderation_status IN ('pending', 'approved', 'flagged', 'rejected')", name='ck_portfolio_images_moderation_status'),
    sa.ForeignKeyConstraint(['collaborator_profile_id'], ['collaborator_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_images_collaborator_profile_id'), ['collaborator_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_images_hash_exacto'), ['hash_exacto'], unique=False)

    with op.batch_alter_table('collaborator_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('foto_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('foto_moderation_status', sa.String(length=10), nullable=False, server_default='approved'))
        batch_op.add_column(sa.Column('foto_moderation_reason', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_collaborator_profiles_foto_hash'), ['foto_hash'], unique=False)
        batch_op.create_check_constraint('ck_collaborator_profiles_foto_moderation_status', "foto_moderation_status IN ('pending', 'approved', 'flagged', 'rejected')")
        batch_op.drop_column('foto_url')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_status', sa.String(length=10), nullable=False, server_default='active'))
        batch_op.create_check_constraint('ck_users_account_status', "account_status IN ('active', 'banned')")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('ck_users_account_status', type_='check')
        batch_op.drop_column('account_status')

    with op.batch_alter_table('collaborator_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint('ck_collaborator_profiles_foto_moderation_status', type_='check')
        batch_op.drop_index(batch_op.f('ix_collaborator_profiles_foto_hash'))
        batch_op.drop_column('foto_moderation_reason')
        batch_op.drop_column('foto_moderation_status')
        batch_op.drop_column('foto_hash')
        batch_op.drop_column('foto_filename')

    with op.batch_alter_table('portfolio_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_images_hash_exacto'))
        batch_op.drop_index(batch_op.f('ix_portfolio_images_collaborator_profile_id'))

    op.drop_table('portfolio_images')
    # ### end Alembic commands ###
